[build]
  command = "bash ./netlify-build.sh"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.1"
  NPM_FLAGS = "--no-audit --production=false"
