[build]
  command = "rm -f package-lock.json next.config.ts && npm install --legacy-peer-deps && npm install @next/swc-linux-x64-gnu @next/swc-linux-x64-musl && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.1"
